# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mainstacks < Formula
  desc "A portable skill library for developers"
  homepage "https://github.com/cjhargre/mainstacks"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.1/mainstacks_0.2.1_darwin_amd64.tar.gz"
      sha256 "d1cae1d5b804bb8a39d2b9b6f163eb098afbe6f3463948d5aa8fed462cd4540a"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.1/mainstacks_0.2.1_darwin_arm64.tar.gz"
      sha256 "ff2fb82e07310b34dd15f1ddad48507dc3eb468338a786c048ab5b99a392f0d2"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.1/mainstacks_0.2.1_linux_amd64.tar.gz"
      sha256 "d2458c4fc6cd039eee953e9f3e973464e5c33a46702827a092e1fa2b20ed725e"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.1/mainstacks_0.2.1_linux_arm64.tar.gz"
      sha256 "27e95b568a42725d89c4d3169b9bba51fd056399af22550fb47307db576fd85e"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end
end
