# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mainstacks < Formula
  desc "A portable skill library for developers"
  homepage "https://github.com/cjhargre/mainstacks"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.0/mainstacks_0.2.0_darwin_amd64.tar.gz"
      sha256 "2a02e69c0d99150f9967bb3296a9e29e0cfd8641f4d4b9d5e3857442883c1807"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.0/mainstacks_0.2.0_darwin_arm64.tar.gz"
      sha256 "6f1a5138b47c8d5461b3c4397a3193e9054e5060d312aaedac16c89f46a4f2db"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.0/mainstacks_0.2.0_linux_amd64.tar.gz"
      sha256 "de48d63918893c7932fc20d4afa4030ec719717badc4de6a7d5df4b214286301"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.2.0/mainstacks_0.2.0_linux_arm64.tar.gz"
      sha256 "c52b0f19ecf53a73f3c43060fa7ae48dc30159ae2bb9ceda2e71748905c88151"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end
end
