# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mainstacks < Formula
  desc "A portable skill library for developers"
  homepage "https://github.com/cjhargre/mainstacks"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.1.1/mainstacks_0.1.1_darwin_amd64.tar.gz"
      sha256 "6a67b64c238846a6545155b657400ec8c7f798b95abb7fcab04529d12c88f004"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.1.1/mainstacks_0.1.1_darwin_arm64.tar.gz"
      sha256 "b5287e831b6a7210821000e6ea2b596d5031a21c3473b78dea1ca8b5996dcce6"

      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.1.1/mainstacks_0.1.1_linux_amd64.tar.gz"
      sha256 "7357ffb929b8c1ddec03dc5535ee85294277832371be74c58569d9d218791330"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjhargreaves/mainstacks/releases/download/v0.1.1/mainstacks_0.1.1_linux_arm64.tar.gz"
      sha256 "90a7b0f451691252fbb95fdb1a66443e802ab3466c5d089cd76ea9e39ab5711a"
      define_method(:install) do
        bin.install "mainstacks"
      end
    end
  end
end
